CANREAD = 1
OWNCARD = 2
CANSETINFO = 4
CANDISCARD = 8
CANMODIFY = 16

INGROUP = 1
GROUPKP = 2
GROUPADMIN = 4
BOTADMIN = 8

STATUS_DEAD = "dead"
STATUS_ALIVE = "alive"
STATUS_SERIOUSLYWOUNDED = "seriously wounded"
STATUS_NEARDEATH = "near-death"
STATUS_TEMPSTABLE = "temporarily stable"
STATUS_PERMANENTINSANE = "permanently insane"

BUTTON_JOB = "b_job"
BUTTON_ADDMAINSKILL = "b_ams"
BUTTON_CGMAINSKILL = "b_cgms"
BUTTON_ADDSGSKILL = "b_ass"
BUTTON_ADDINTSKILL = "b_ais"
BUTTON_CGINTSKILL = "b_cgis"
BUTTON_CHOOSEDEC = "b_cdec"
BUTTON_SETDEC = "b_sdec"
BUTTON_DISCARD = "b_dcd"
BUTTON_SWITCH = "b_swh"
BUTTON_SWITCHGAMECARD = "b_swhgc"
BUTTON_SETSEX = "b_ssx"
BUTTON_MANUAL = "b_mnl"

PLTYPE = "PL"
NPCTYPE = "NPC"